# Generated by Django 5.0.3 on 2024-06-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='image',
            field=models.ImageField(default='', upload_to='receipe'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipdes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
